# For making a post request to login a user
POST http://localhost:5000/api/users/login
content-type: application/json

{
    "email": "favour@gmail.com",
    "password": "admin12345"
}

###

# For making a post request to register a new user
POST http://localhost:5000/api/users/register
content-type: application/json

{
    "email": "andy@gmail.com",
    "name": "andy",
    "password": "admin12345",
    "password2": "admin12345"
}

###

# for making a get request to get the current logged in user
GET http://localhost:5000/api/users/current
content-type: application/json

###

# For making a post request to the profile route
POST http://localhost:5000/api/profile
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNWUxNTYzYjY1YjhiMDI4Y2EzMzZiMyIsIm5hbWUiOiJmYXZvdXIiLCJpYXQiOjE2MDAwMTI4MjgsImV4cCI6MTYwMDAxNjQyOH0.RQfBqHL64bO_9flMd62MX6fjfDzzkKXaWH-gPf7dxAM

{
    "handle": "favouristic",
    "status": "Content Creator",
    "skills": "SEO, social media marketing",
    "location": "Abuja",
    "company": "E4e",
    "website": "favour.herokuapp.com",
    "twitter": "twitter.com/favour",
    "facebook": "facebook.com/favour"
}

###

# For making a get request to the profile route
GET http://localhost:5000/api/profile
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNWUxNTYzYjY1YjhiMDI4Y2EzMzZiMyIsIm5hbWUiOiJmYXZvdXIiLCJpYXQiOjE2MDAwMTI4MjgsImV4cCI6MTYwMDAxNjQyOH0.RQfBqHL64bO_9flMd62MX6fjfDzzkKXaWH-gPf7dxAM
###

# for getting a single user by handle name
GET http://localhost:5000/api/profile/handle/baron
Content-type: application/json

###

# for getting a single user by user_id
GET http://localhost:5000/api/profile/user/5f5e03d2e2fe891f90a4f2b2
Content-type: application/json

###
# for getting a single user by user_id
GET http://localhost:5000/api/profile/all
Content-type: application/json

###

# For making a post request to the profile route 
POST http://localhost:5000/api/profile/experience
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNWUxNTYzYjY1YjhiMDI4Y2EzMzZiMyIsIm5hbWUiOiJmYXZvdXIiLCJpYXQiOjE2MDAwMTgxNzksImV4cCI6MTYwMDYyMjk3OX0.mBATJnVHMUp8TWQ3MfgPTnLWXkKw2xQNiSt0RoPN5Qo
   
{
    "title": "Data Analyst",
    "company": "DigiDelta",
    "from": "12/01/2019"
}


###
# For making a post request to the profile route 
POST http://localhost:5000/api/profile/education
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNWUxNTYzYjY1YjhiMDI4Y2EzMzZiMyIsIm5hbWUiOiJmYXZvdXIiLCJpYXQiOjE2MDAwMTI4MjgsImV4cCI6MTYwMDAxNjQyOH0.RQfBqHL64bO_9flMd62MX6fjfDzzkKXaWH-gPf7dxAM
   
{
    "school": "federal university of technology ",
    "degree": "B.Tech",
    "fieldofstudy": "Geology",
    "from": "2009-09-23",
    "to": "2014-04-15",
    "description": "Was a serious stuff"
}


###

# For deleting a single experience from list of users experience
DELETE http://localhost:5000/api/profile/experience/5f5e572bb479e703b0a65a06
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNWUxNTYzYjY1YjhiMDI4Y2EzMzZiMyIsIm5hbWUiOiJmYXZvdXIiLCJpYXQiOjE2MDAwMTgxNzksImV4cCI6MTYwMDYyMjk3OX0.mBATJnVHMUp8TWQ3MfgPTnLWXkKw2xQNiSt0RoPN5Qo

###

# For deleting a single education from list of users education
DELETE http://localhost:5000/api/profile/education/5f5e4e8015aca4225803473f
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNWUxNTYzYjY1YjhiMDI4Y2EzMzZiMyIsIm5hbWUiOiJmYXZvdXIiLCJpYXQiOjE2MDAwMTgxNzksImV4cCI6MTYwMDYyMjk3OX0.mBATJnVHMUp8TWQ3MfgPTnLWXkKw2xQNiSt0RoPN5Qo
